apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: terraform-controller
spec:
  forProvider:
    chart:
      name: terraform-controller
      repository: https://smsilva.github.io/helm
      version: 0.1.3
    namespace: default
