apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: wordpress-example
spec:
  forProvider:
    chart:
      name: wordpress
      repository: https://charts.bitnami.com/bitnami
      version: 9.3.19
    #     pullSecretRef:
    #       name: museum-creds
    #       namespace: default
    #     url: "https://charts.bitnami.com/bitnami/wordpress-9.3.19.tgz"
    namespace: wordpress
    #   skipCreateNamespace: true
    wait: true
    values:
      service:
        type: ClusterIP
    set:
      - name: param1
        value: value2
