apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: stackconfigs.terraform.silvios.me
spec:
  compositeTypeRef:
    apiVersion: terraform.silvios.me/v1alpha1
    kind: StackConfig
  resources:
    - base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: configmapname
                namespace: default
              data:
                region: configregioname

      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.region
          toFieldPath: spec.forProvider.manifest.data.region

        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.manifest.metadata.name
