apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-provider-helm-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: provider-helm-sa
    namespace: crossplane-system

  - kind: ServiceAccount
    name: provider-kubernetes-sa
    namespace: crossplane-system
