---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-helm-sa
  namespace: crossplane-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-kubernetes-sa
  namespace: crossplane-system
