---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-helm-sa
  namespace: crossplane
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-kubernetes-sa
  namespace: crossplane
