apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: clusters.kubernetes.silvios.me
spec:
  connectionSecretKeys:
    - kubeconfig
  group: kubernetes.silvios.me
  names:
    kind: Cluster
    listKind: ClusterList
    plural: clusters
    singular: cluster
    shortNames: []
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: A Cluster is a composite resource that represents a Kubernetes Cluster
          type: object
          properties:
            spec:
              type: object
              properties:
                region:
                  type: string
                  description: region in which the Kubernetes Cluster will be created
              required:
                - region
