apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: clusters.kubernetes.silvios.me
spec:
  writeConnectionSecretsToNamespace: default
  compositeTypeRef:
    apiVersion: kubernetes.silvios.me/v1alpha1
    kind: Cluster
  resources:
    - base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: Namespace
          providerConfigRef:
            name: default
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.manifest.metadata.name
          transforms:
            - type: string
              string:
                fmt: "kubernetes-cluster-%s"
